const studentList = [
  { name: "ANANYA B", rollNo: 1 },
  { name: "ARPITHA S", rollNo: 2 },
  { name: "BHUVAN SHETTY", rollNo: 3 },
  { name: "BIYA JOHNSON", rollNo: 4 },
  { name: "CHANDAN KUMAR P", rollNo: 5 },
  { name: "DARSHAN V", rollNo: 6 },
  { name: "HS KRUPA", rollNo: 7 },
  { name: "JAYASHREE N", rollNo: 8 },
  { name: "JENITA VENITA DCOSTA", rollNo: 9 },
  { name: "JOVITA REEMA DCOSTA", rollNo: 10 },
  { name: "KAWSHIK A M", rollNo: 11 },
  { name: "KEERTHAN H", rollNo: 12 },
  { name: "KIRAN K", rollNo: 13 },
  { name: "KRITHI N", rollNo: 14 },
  { name: "KRUTHIKA K J", rollNo: 15 },
  { name: "LIKHITHA", rollNo: 16 },
  { name: "LOHITH KUMAR", rollNo: 17 },
  { name: "NEEKSHA", rollNo: 18 },
  { name: "NISHA MR", rollNo: 19 },
  { name: "PAVAN U P", rollNo: 20 },
  { name: "PRUTHVIK", rollNo: 21 },
  { name: "RADHIKA KR", rollNo: 22 },
  { name: "RAMYA K", rollNo: 23 },
  { name: "RANJEETH", rollNo: 24 },
  { name: "SANATH P V", rollNo: 25 },
  { name: "SARTHAK B", rollNo: 26 },
  { name: "SHARANYA B", rollNo: 27 },
  { name: "SHIVANI BT", rollNo: 28 },
  { name: "SHREERANJAN", rollNo: 29 },
  { name: "SHRADDHA B D", rollNo: 30 },
  { name: "SINCHANA L", rollNo: 31 },
  { name: "THRIPTHI", rollNo: 32 },
  { name: "VANDYA M", rollNo: 33 },
  { name: "VIBHASHREE MS", rollNo: 34 },
  { name: "VIKHYA G C", rollNo: 35 },
  { name: "YUKTHA I P", rollNo: 36 },
];



export default studentList;